# Generated by Django 4.2.3 on 2024-01-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='additional_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Дополнительный файл'),
        ),
    ]
