# Generated by Django 4.2.3 on 2023-11-25 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=30, verbose_name='Врач')),
                ('date', models.CharField(help_text='Формат: XX.XX.XXXX', max_length=10, verbose_name='Дата')),
                ('time', models.CharField(help_text='Формат: XX.XX', max_length=5, verbose_name='Время')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('office_number', models.CharField(max_length=6, verbose_name='Кабинет')),
                ('health_troubles', models.TextField(blank=True, verbose_name='Жалобы')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
