# Generated by Django 4.2.3 on 2023-12-13 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('baseentitymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='welcome.baseentitymodel')),
                ('doctor', models.CharField(max_length=14, verbose_name='Врач')),
                ('date', models.DateField(help_text='Формат: XX.XX.XXXX', verbose_name='Дата')),
                ('time', models.TimeField(help_text='Формат: XX:XX', verbose_name='Время')),
                ('address', models.CharField(max_length=80, verbose_name='Адрес')),
                ('office_number', models.CharField(max_length=6, verbose_name='Кабинет')),
                ('health_troubles', models.TextField(blank=True, null=True, verbose_name='Жалобы')),
                ('report', models.TextField(blank=True, null=True, verbose_name='Отчет после приема')),
            ],
            options={
                'verbose_name': 'Запись к врачу',
                'verbose_name_plural': 'Записи к врачу',
            },
            bases=('welcome.baseentitymodel',),
        ),
    ]
