# Generated by Django 4.2.3 on 2023-11-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Архивировано?'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(help_text='Формат: XX.XX.XXXX', max_length=10, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(help_text='Формат: XX:XX', max_length=5, verbose_name='Время'),
        ),
    ]
