# Generated by Django 4.2.3 on 2023-11-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_appointment', '0002_appointment_archived_alter_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='report',
            field=models.TextField(blank=True, null=True, verbose_name='Отчет после приема'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='health_troubles',
            field=models.TextField(blank=True, null=True, verbose_name='Жалобы'),
        ),
    ]
