# Generated by Django 4.2.3 on 2023-11-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_appointment', '0003_appointment_report_alter_appointment_health_troubles'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_ended',
            field=models.BooleanField(default=False, editable=False, verbose_name='Закончился ли прием?'),
        ),
    ]
