# Generated by Django 4.2.3 on 2023-11-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_appointment', '0004_appointment_is_ended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='is_ended',
            field=models.BooleanField(default=False, verbose_name='Закончился ли прием?'),
        ),
    ]
