# Generated by Django 4.2.3 on 2023-12-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_appointment', '0005_alter_appointment_is_ended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='address',
            field=models.CharField(max_length=80, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(max_length=14, verbose_name='Врач'),
        ),
    ]
