# Generated by Django 4.2.3 on 2023-12-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_appointment', '0006_alter_appointment_address_alter_appointment_doctor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Запись к врачу', 'verbose_name_plural': 'Записи к врачу'},
        ),
    ]
