# Generated by Django 4.2.3 on 2023-12-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors_appointment', '0007_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(help_text='Формат: XX.XX.XXXX', verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(help_text='Формат: XX:XX', verbose_name='Время'),
        ),
    ]
