# Generated by Django 4.2.3 on 2023-12-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Название')),
                ('end_date', models.DateField(verbose_name='Последний день приема')),
                ('amount_per_day', models.CharField(help_text='Может содержать как число, так и описание: 2 таблетки в 3 дня', max_length=20, verbose_name='Кол-во раз в день')),
                ('dosage', models.CharField(help_text='Например: 3 капсулы', max_length=30, verbose_name='Дозировка за один прием')),
                ('comments', models.TextField(verbose_name='Комментарии')),
                ('is_ended', models.BooleanField(default=False, verbose_name='Прием лекарства закончился?')),
            ],
        ),
    ]
