# Generated by Django 4.2.3 on 2023-12-11 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicine', '0002_alter_medicine_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='patient',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to=settings.AUTH_USER_MODEL, verbose_name='пациент'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='amount_per_day',
            field=models.CharField(help_text='Может содержать как число, так и описание: 2 таблетки в 3 дня', max_length=40, verbose_name='Кол-во раз в день'),
        ),
    ]
