# Generated by Django 4.2.3 on 2023-12-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_medicine_patient_alter_medicine_amount_per_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='name',
            new_name='title',
        ),
    ]
