### 
POST http://127.0.0.1:8000/api/login/
content-type: application/json
{
    "username": "admin",
    "password": "admin"
}
###

GET http://127.0.0.1:8000/api/users
content-type: application/json
Authorization: Token 783b6e6b7e7c66f5f1bcc914822eca5ef84fb5b3
###

GET http://127.0.0.1:8000/api/groups
Content-Type: application/json
Authorization: Token 783b6e6b7e7c66f5f1bcc914822eca5ef84fb5b3
### 